// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 02.03.2026, 17:01:51
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.cjs";
const config = [
{"content":{"files":["C:/Users/Alex/Desktop/work/mini_bitrix_landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Alex/Desktop/work/mini_bitrix_landing/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Alex/Desktop/work/mini_bitrix_landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Alex/Desktop/work/mini_bitrix_landing/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Alex/Desktop/work/mini_bitrix_landing/plugins/**/*.{js,ts,mjs}","C:/Users/Alex/Desktop/work/mini_bitrix_landing/composables/**/*.{js,ts,mjs}","C:/Users/Alex/Desktop/work/mini_bitrix_landing/utils/**/*.{js,ts,mjs}","C:/Users/Alex/Desktop/work/mini_bitrix_landing/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Alex/Desktop/work/mini_bitrix_landing/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Alex/Desktop/work/mini_bitrix_landing/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Alex/Desktop/work/mini_bitrix_landing/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;